config/routes.rb
Rails.application.routes.draw do
  resources :sightings do
    get :get_sightings, on: :collection
  end
  resources :animals
  get "calendar" => "animals#calendar"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'animals#index'
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_many :sightings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sighting.rb
class Sighting < ApplicationRecord
  belongs_to :animal
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  def calendar
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:common_name, :latin_name, :kingdom)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  before_action :set_sighting, only: [:show, :edit, :update, :destroy]

  # GET /sightings
  # GET /sightings.json
  def index
    @sightings = Sighting.all
  end

  def get_sightings
    @sightings = Sighting.all
    sightings = []
    @sightings.each do |sighting|
      sightings << { id: sighting.id, start: sighting.date, title: sighting.animal.common_name, latitude: sighting.latitude, longitude: sighting.longitude, url: Rails.application.routes.url_helpers.sighting_path(sighting.id)}
    end
    render :json => sightings.to_json
  end

  # GET /sightings/1
  # GET /sightings/1.json

    def show
    end

  # GET /sightings/new
  def new
    @sighting = Sighting.new
    @sightings_for_select = Animal.all.map do |animal|
      [animal.common_name, animal.id]
    end
    @regions_for_select = ['NorthWest', 'NorthEast'].map do |region|
      [region, region]
    end
  end

  # GET /sightings/1/edit
  def edit
    @sightings_for_select = Animal.all.map do |animal|
      [animal.common_name, animal.id]
    end
    @regions_for_select = ['NorthWest', 'NorthEast'].map do |region|
      [region, region]
    end
  end

  # POST /sightings
  # POST /sightings.json
  def create
    @sighting = Sighting.new(sighting_params)

    respond_to do |format|
      if @sighting.save
        format.html { redirect_to @sighting, notice: 'Sighting was successfully created.' }
        format.json { render :show, status: :created, location: @sighting }
      else
        format.html { render :new }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sightings/1
  # PATCH/PUT /sightings/1.json
  def update
    respond_to do |format|
      if @sighting.update(sighting_params)
        format.html { redirect_to @sighting, notice: 'Sighting was successfully updated.' }
        format.json { render :show, status: :ok, location: @sighting }
      else
        format.html { render :edit }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sightings/1
  # DELETE /sightings/1.json
  def destroy
    @sighting.destroy
    respond_to do |format|
      format.html { redirect_to sightings_url, notice: 'Sighting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sighting
      @sighting = Sighting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sighting_params
      params.require(:sighting).permit(:date, :time, :latitude, :longitude, :region, :animal_id)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/views/animals/_form.html.erb
<%= form_for(animal, remote: true) do |f| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :common_name %>
    <%= f.text_field :common_name %>
  </div>

  <div class="field">
    <%= f.label :latin_name %>
    <%= f.text_field :latin_name %>
  </div>

  <div class="field">
    <%= f.label :kingdom %>
    <%= f.text_field :kingdom %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/animals/calendar.html.erb
<div id="calendar"></div>

<br>

<%= link_to 'Home', root_path %> | <%= link_to 'Animal Sightings', sightings_path %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
  <p id="notice"><%= notice %></p>

<h1>Animals</h1>

<table id="animal_list">
  <thead>
    <tr>
      <th>Common name</th>
      <th>Latin name</th>
      <th>Kingdom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= animal.common_name %></td>
        <td><%= animal.latin_name %></td>
        <td><%= animal.kingdom %></td>
        <td><%= link_to 'Show', animal %></td>
        <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
        <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', root_path %> | <%= link_to 'Animal Sightings', sightings_path %> | <%= link_to 'Sightings Calendar', calendar_path %> | <%= link_to 'Create New Animal', new_animal_path %>

<hr>

<h3>Add an Animal with AJAX</h3>
<p>
  <!-- Input area for new animal -->
  <div class="field">
    <label for="common_name">Common Name</label>
    <input type="text" name="animal[common_name]" id="common_name" />
  </div>
  <div class="field">
    <label for="latin_name">Latin Name</label>
    <input type="text" name="animal[latin_name]" id="latin_name" />
  </div>
  <div class="field">
    <label for="kingdom">Kingdom</label>
    <input type="text" name="animal[kingdom]" id="kingdom" />
  </div>

  <button id="add_new_animal_button">Create New Animal</button>
</p>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Common name:</strong>
  <%= @animal.common_name %>
</p>

<p>
  <strong>Latin name:</strong>
  <%= @animal.latin_name %>
</p>

<p>
  <strong>Kingdom:</strong>
  <%= @animal.kingdom %>
</p>

<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wildlife</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sightings/_form.html.erb
<%= form_for(sighting) do |f| %>
  <% if sighting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sighting.errors.count, "error") %> prohibited this sighting from being saved:</h2>

      <ul>
      <% sighting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

  <div class="field">
    <%= f.label :time %>
    <%= f.datetime_select :time %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :region %>
    <%= f.select(:region, @regions_for_select) %>
  </div>

  <div class="field">
    <%= f.label :animal_id %>
    <%= f.select(:animal_id, @sightings_for_select) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sightings/edit.html.erb
<h1>Editing Sighting</h1>

<%= render 'form', sighting: @sighting %>

<%= link_to 'Show', @sighting %> |
<%= link_to 'Back', sightings_path %>

app/views/sightings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sightings</h1>

<table id="sighting_list">
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Animal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sightings.each do |sighting| %>
      <tr>
        <td><%= sighting.date.strftime("%m/%d/%Y") %></td>
        <td><%= sighting.time.strftime("%I:%M%P") %></td>
        <td><%= sighting.latitude %></td>
        <td><%= sighting.longitude %></td>
        <td><%= sighting.animal.common_name %></td>
        <td><%= link_to 'Show', sighting %></td>
        <td><%= link_to 'Edit', edit_sighting_path(sighting) %></td>
        <td><%= link_to 'Destroy', sighting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', root_path %> | <%= link_to 'Sightings Calendar', calendar_path %> | <%= link_to 'Add New Sighting', new_sighting_path %>

<hr>

<h3>Add an Animal Sighting with AJAX</h3>
<p>
  <!-- Input area for new sighting -->
  <div class="field">
    <label for="date">Date</label>
    <input type="date" name="sighting[date]" id="date" />
  </div>
  <div class="field">
    <label for="time">Time</label>
    <input type="time" name="sighting[time]" id="time" />
  </div>
  <div class="field">
    <label for="latitude">Latitude</label>
    <input type="number" name="sighting[latitude]" id="latitude" />
  </div>
  <div class="field">
    <label for="longitude">Longitude</label>
    <input type="number" name="sighting[longitude]" id="longitude" />
  </div>
  <div class="field">
    <label for="Animal">Animal</label>
    <input type="number" name="sighting[animal_id]" id="animal_id" />
  </div>

  <button id="add_new_sighting_button">Create New Sighting</button>
</p>

app/views/sightings/new.html.erb
<h1>New Sighting</h1>

<%= render 'form', sighting: @sighting %>

<%= link_to 'Back', sightings_path %>

app/views/sightings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @sighting.date.strftime("%m/%d/%Y") %>
</p>

<p>
  <strong>Time:</strong>
  <%= @sighting.time.strftime("%I:%M%P") %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @sighting.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @sighting.longitude %>
</p>

<p>
  <strong>Region</strong>
  <%= @sighting.region %>
</p>

<p>
  <strong>Animal:</strong>
  <%= @sighting.animal.common_name %>
</p>

<%= link_to 'Edit', edit_sighting_path(@sighting) %> |
<%= link_to 'Back', sightings_path %>